name: Veracode Policy Scan  ✅

on:
  workflow_dispatch:

jobs:
  policy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Zip Project
        run: zip -r project.zip . 

      - name: Debugging
        run: |
          echo "App Name: ${{ secrets.VERACODE_API_ID }}"
          echo "File Path: project.zip"
          ls -l 

      - name: Run Veracode Policy Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'cloudgoad'  # Confirme o nome correto do app no Veracode
          filepath: 'project.zip'
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"
          scantimeout: 15
          createprofile: true  # Garante que o perfil do app seja criado
